/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#99907c',
        'on-secondary-container': '#ffdcd7',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-variant': '#353534',
        secondary: '#ffb4a8',
        'on-tertiary-container': '#444546',
        'on-primary-container': '#554300',
        background: '#131313',
        'primary-fixed-dim': '#e9c349',
        'on-surface': '#e5e2e1',
        'surface-tint': '#e9c349',
        'primary-fixed': '#ffe088',
        'secondary-container': '#ce0301',
        'on-primary-fixed': '#241a00',
        'tertiary-container': '#b3b3b3',
        'on-tertiary': '#2f3131',
        surface: '#131313',
        'surface-container-highest': '#353534',
        'tertiary-fixed-dim': '#c7c6c6',
        'on-tertiary-fixed-variant': '#464747',
        'secondary-fixed-dim': '#ffb4a8',
        'on-primary-fixed-variant': '#574500',
        error: '#ffb4ab',
        'on-error': '#690005',
        'on-surface-variant': '#d0c5af',
        'on-secondary': '#690000',
        primary: '#f2ca50',
        'surface-container': '#201f1f',
        'surface-bright': '#3a3939',
        'on-background': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e1',
        'primary-container': '#d4af37',
        'surface-dim': '#131313',
        'surface-container-low': '#1c1b1b',
        'inverse-primary': '#735c00',
        'inverse-on-surface': '#313030',
        'error-container': '#93000a',
        'tertiary-fixed': '#e3e2e2',
        'on-secondary-fixed': '#410000',
        'on-primary': '#3c2f00',
        'outline-variant': '#4d4635',
        'secondary-fixed': '#ffdad4',
        tertiary: '#cfcece',
        'on-secondary-fixed-variant': '#930000',
        'surface-container-lowest': '#0e0e0e',
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'section-gap': '120px',
        gutter: '24px',
      },
      fontFamily: {
        headline: ['Oswald', 'sans-serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
        label: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['80px', { lineHeight: '88px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      boxShadow: {
        glow: '0 0 20px rgba(242, 202, 80, 0.3)',
        'glow-sm': '0 0 15px rgba(242, 202, 80, 0.2)',
        'glow-lg': '0 0 30px rgba(242, 202, 80, 0.35)',
        'glow-red': '0 0 25px rgba(206, 3, 1, 0.4)',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.25' },
        },
        'badge-in': {
          '0%': { opacity: '0', transform: 'scale(0.6) rotate(-8deg)' },
          '60%': { opacity: '1', transform: 'scale(1.06) rotate(2deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
        },
      },
      animation: {
        blink: 'blink 1.2s ease-in-out infinite',
        'badge-in': 'badge-in 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
    },
  },
  plugins: [],
};
