import type { MasterProfile, Service } from '@/types';

export const FALLBACK_SERVICES: Service[] = [
  {
    id: 'svc-signature-cut',
    nameEn: 'Signature Haircut',
    nameRu: 'Фирменная стрижка',
    descriptionEn:
      'Meticulous clipper and shear work tailored to your specific bone structure and style preference. Includes a hot towel neck shave.',
    descriptionRu:
      'Тщательная работа машинкой и ножницами с учётом формы головы и предпочтений в стиле. Включает горячее полотенце.',
    basePriceCents: 4500,
    baseDurationMinutes: 45,
    category: 'hair',
    icon: 'content_cut',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'svc-beard-trim',
    nameEn: 'Executive Beard Trim',
    nameRu: 'Executive-оформление бороды',
    descriptionEn:
      'Sculpting, lining, and fading of the beard. Finished with straight razor detailing on the cheeks and neck, followed by premium beard oil.',
    descriptionRu:
      'Моделирование, контур и фейд бороды. Финальная обработка опасной бритвой и премиальным маслом для бороды.',
    basePriceCents: 3000,
    baseDurationMinutes: 30,
    category: 'beard',
    icon: 'face',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'svc-hot-towel-shave',
    nameEn: 'Hot Towel Shave',
    nameRu: 'Бритьё горячим полотенцем',
    descriptionEn:
      'The traditional barbering experience. Multiple hot towels, rich lather, and a flawlessly smooth straight razor shave.',
    descriptionRu:
      'Традиционный барберинг. Несколько горячих полотенец, густая пена и безупречно гладкое бритьё опасной бритвой.',
    basePriceCents: 5000,
    baseDurationMinutes: 40,
    category: 'shave',
    icon: 'water_drop',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'svc-skin-fade',
    nameEn: 'Precision Skin Fade',
    nameRu: 'Точный скин-фейд',
    descriptionEn: 'Zero-grade fade with razor-sharp line work, blended seamlessly into any length on top.',
    descriptionRu: 'Фейд под ноль с чёткими линиями, безупречно сочетающийся с любой длиной волос сверху.',
    basePriceCents: 4000,
    baseDurationMinutes: 40,
    category: 'hair',
    icon: 'design_services',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'svc-kids-cut',
    nameEn: 'Junior Cut',
    nameRu: 'Детская стрижка',
    descriptionEn: 'A sharp, patient cut for the next generation. Ages 12 and under.',
    descriptionRu: 'Аккуратная стрижка для нового поколения. Возраст до 12 лет.',
    basePriceCents: 2500,
    baseDurationMinutes: 25,
    category: 'hair',
    icon: 'child_care',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'svc-full-service',
    nameEn: 'The Full Level Up',
    nameRu: 'Полный Level Up',
    descriptionEn: 'Signature haircut, beard sculpt, and hot towel shave in one uncompromising session.',
    descriptionRu: 'Фирменная стрижка, оформление бороды и бритьё горячим полотенцем в одной сессии.',
    basePriceCents: 9500,
    baseDurationMinutes: 90,
    category: 'package',
    icon: 'workspace_premium',
    isActive: true,
    sortOrder: 6,
  },
];

export const FALLBACK_MASTERS: MasterProfile[] = [
  {
    id: 'master-shaxzod',
    userId: 'user-shaxzod',
    name: 'Shaxzod Asliev',
    nameEn: 'Shaxzod Asliev',
    nameRu: 'Шахзод Аслиев',
    bio: 'Owner barber at Level Up — precision cuts, fades, and beard work.',
    photoUrl: null,
    specialtyTags: ['FADES', 'CLASSIC CUTS', 'BEARD'],
    instagramHandle: '@shaxa__24',
    isActive: true,
    sortOrder: 1,
    rating: 5.0,
    services: FALLBACK_SERVICES,
  },
];
